### ISSUE TITLE
Impossible to add an agenda (ordre du jour) to a meeting on cerise.osp.cat

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#223] opened 2018-09-04 10:22 UTC
I updated the agenda of this meeting here https://cerise.osp.cat/admin/participatory_processes/processus-test/components/86/manage/meetings/48/agenda/1/edit
The update seems to work but then on the show of the meeting, the "ordre du jour" doesn't appear here https://cerise.osp.cat/processes/processus-test/f/86/meetings/48

I did a test on demo and everything works fine so it seems to be an issue only on cerise.osp.cat

**Comment by armandfardeau** [comment] 2018-09-05 09:20
@juliesimon @moustachu What is the current Decidim version? Should we update it?

**Comment by armandfardeau** [comment] 2018-10-01 09:28
> @juliesimon @moustachu What is the current Decidim version? Should we update it?

@lu-hamani Would you mind checking if this issue is still around?

**Comment by lu-hamani** [comment] 2018-10-04 11:56
@armandfardeau 
I can confirm that the issue is still around as described by Julie

**Comment by armandfardeau** [comment] 2018-11-19 14:54
The visible check need to be ... checked ;)
![image](https://user-images.githubusercontent.com/20232956/48714646-694d2f80-ec13-11e8-9639-00f2b07cb83b.png)
-> closing

**Closed by armandfardeau** 2018-11-19 14:54 UTC
Labels: Blocking Bug, component: meetings
