### ISSUE TITLE
Server errror when asking for registration on a meeting

### ISSUE THREAD

**Issue by leokante** [OpenSourcePolitics/decidim#673] opened 2019-05-29 09:07 UTC
**Describe the bug**
"Il y a eu un problème avec notre serveur" is displayed when asking for registration on a meeting. 

**To Reproduce**
1. Go to https://decidim.democracyos.fr/processes/exemple-asso/f/19/meetings/5
2. Click on 'participer à la rencontre'

**Expected behavior**
I don't remember what is supposed to be displayed instead of this error. 

**Screenshots**
![image](https://user-images.githubusercontent.com/43004803/58544548-cb5da180-8201-11e9-8e95-1c4f1abd045d.png)

**Stacktrace**
If applicable, add the error stacktrace to help explain your problem.

**Extra data (please complete the following information):**
 - Device: [Desktop]
 - Device OS: [Windows 10]
 - Browser: [Safari]
 - Decidim Version: [0.16]
 - Decidim installation: [agorasso] 
(https://decidim.democracyos.fr/)

**Comment by moustachu** [comment] 2019-06-03 14:12
https://sentry.io/organizations/open-source-politics/issues/1047699589/?environment=production&project=1442772&query=is%3Aunresolved

**Comment by armandfardeau** [comment] 2019-06-11 13:42
@moustachu @leokante This problem was caused by an empty registration form on this event. I disabled it, this bug is not present on 0.16-stable so I suggest an update.

This issue has been temporarily fixed by disabling the registration form.

**Closed by armandfardeau** 2019-06-11 13:42 UTC
Labels: 0.16-stable, Blocking Bug
